sudo: false
language: php
php:
  - 7.0
  - 7.1

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer install

script:
  - phpcs -n --standard=PEAR src
  - pwd
  - ./vendor/bin/phpunit test
