sudo: false
language: php
php:
  - 7.2
  - 7.3
  - 7.4
dist: bionic

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer selfupdate --1
  - composer install

script:
  - phpcs -n --standard=PEAR src
  - ./vendor/bin/phpunit test
